name: Action to test the Python client
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: sudo apt-get update
      - run: sudo apt-get install -y mosquitto

      - run: sudo apt-get install -y python3 python3-pip
      - run: pip install git+https://github.com/behave/behave
      - run: pip install PyHamcrest
      - run: pip install coverage
      - run: pip install loguru

      - run: export PYTHONPATH=`pwd`
      - run: echo "PYTHONPATH=$PYTHONPATH"

      - run: pip install git+https://github.com/Panduza/panduza-py

      - run: sudo mkdir -p /etc/panduza
      - run: sudo touch /etc/panduza/tree.json
      - run: sudo chown $USER /etc/panduza/tree.json

      - run: behave
      - run: coverage report

      - run: behave -f html -o test_reports/test.html
      - run: coverage html -d test_reports/coverage

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test_reports
          path: test_reports

      - run: echo "🎉 Test finished !"

